spring.application.name=platform
 
server.port=8080
 
# --- Database (update credentials as needed)
spring.datasource.url=jdbc:postgresql://localhost:5432/project_intelligence
 
spring.datasource.username=postgres
spring.datasource.password=agam
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
 
# --- JWT
app.jwt.secret=mySuperSecretKeyForJwtAuthentication123456
app.jwt.expiration-ms=3600000
# 
# --- Python ML Service
app.ml.base-url=http://localhost:8000